#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Nov 18, 2019 03:13:45 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -background #000000 -highlightbackground #000000 \
        -highlightcolor #000000 -padx 0 -pady 0 
    wm focusmodel $top passive
    wm geometry $top 703x598+420+55
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1080 1920
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra52 \
        -background #bebef3 -height 135 -padx 0 -pady 0 -width 1005 
    vTcl:DefineAlias "$top.fra52" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    frame $site_3_0.fra55 \
        -background #fbb7db -width 125 
    vTcl:DefineAlias "$site_3_0.fra55" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra55
    label $site_4_0.lab57 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text INSERT_TEMP 
    vTcl:DefineAlias "$site_4_0.lab57" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab57 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.1 -width 0 -relwidth 0.8 \
        -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    frame $site_3_0.fra56 \
        -background #bef3ce -height 75 -width 125 
    vTcl:DefineAlias "$site_3_0.fra56" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra56
    label $site_4_0.lab58 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text INSERT_HEAT_STREAM 
    vTcl:DefineAlias "$site_4_0.lab58" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab58 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.1 -width 0 -relwidth 0.8 \
        -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $site_3_0.fra55 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.25 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $site_3_0.fra56 \
        -in $site_3_0 -x 0 -relx 0.75 -y 0 -width 0 -relwidth 0.25 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra52 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.2 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

